### ISSUE TITLE
Problem to create routings

### ISSUE THREAD

**Issue by kotsmile** [RobinTail/express-zod-api#1121]
I want to combine 
```
GET /api/users
POST /api/users
GET /api/users/:id
PATCH /api/users/:id
DELETE /api/users/:id
```
With current architecture of routings it seems impossible

**Comment by RobinTail** [comment]
@kotsmile ,

you need to read the following two articles in order to achieve the desired configuration:

1. https://github.com/RobinTail/express-zod-api#multiple-schemas-for-one-route
2. https://github.com/RobinTail/express-zod-api#route-path-params

This should help you to make it possible.
If not, please let me know in another issue.

**Comment by RobinTail** [comment]
```ts
const routing: Routing = {
  api: {
    users: {
      "": new DependsOnMethod({
        get: getUsersEndpoint,
        post: makeUsersEndpoint,
      }),
      ":id": new DependsOnMethod({
        get: getUserByIdEndpoint,
        patch: changeUserByIdEndpoint,
        delete: deleteUserByIdEndpoint,
      })
    }
  }
}
```

@kotsmile

**Comment by kotsmile** [comment]
And I'm also in the process of writing an autorouting generator depending on the file structure, if it's useful I may add MR later on

**Comment by RobinTail** [comment]
> perhaps need to add such an example to the documentation

I tried my best.

![image](https://github.com/RobinTail/express-zod-api/assets/13189514/67e634fc-c0f9-4825-9c46-c4d08b031048)

I'm open to other suggestions.
