### ISSUE TITLE
Unable to use .array() as return type

### ISSUE THREAD

**Issue by akanoce** [RobinTail/express-zod-api#619]
Hello and thanks for building this package, i was looking for something like this since a while.
It looks like i'm unable to use a zod array as an endpoint return type.
```

 const updateUserEndpoint = basicEndpointsFactory.build({
    method: "put",
    input: z.object({}),
    output: z.object({ test: z.string() }).array(),
    handler: async ({ options, logger, input }) => {
//.....
}
)}
```
gives me a typerror on the output key, with the following output 
```
Type 'ZodArray<ZodObject<{ test: ZodString; }, "strip", ZodTypeAny, { test: string; }, { test: string; }>, "many">' is not assignable to type 'IOSchema<any>'.
  Type 'ZodArray<ZodObject<{ test: ZodString; }, "strip", ZodTypeAny, { test: string; }, { test: string; }>, "many">' is missing the following properties from type 'ZodDiscriminatedUnion<string, Primitive, ZodObject<any, any, ZodTypeAny, { [x: string]: any; }, { [x: string]: any; }>>': discriminator, validDiscriminatorValues, optionsts(2322)
endpoints-factory.d.ts(12, 5): The expected type comes from property 'output' which is declared here on type 'BuildProps<ZodObject<{}, "strip", ZodTypeAny, {}, {}>, IOSchema<any>, ZodObject<{}, "strip", ZodTypeAny, {}, {}>, { ...; }, "put", string>'
```
Unfortunately, `.array` does not exist on type ZodObject, if i remember correctly` AnyZodObject` should be the right type in order to accept every zod schema. 
Am i doing something wrong or this is an intended behavior? 
Thanks in advance!

**Comment by RobinTail** [comment]
Hello @akanoce ,

This is intentional, [read here why](https://github.com/RobinTail/express-zod-api/discussions/361#discussioncomment-2396404).
However. [in the same thread](https://github.com/RobinTail/express-zod-api/discussions/361#discussioncomment-2395687) you may find a workaround in case you still wanna do it.

Perhaps I'll make another build-in ResultHandler for the cases like this in the future.
But I still recommend avoiding this as a bad practice.
In case you have any suggestions or additional thoughts on the topic, please write them into [the discussion](https://github.com/RobinTail/express-zod-api/discussions/361).
