### ISSUE TITLE
Accepting a request body for a DELETE endpoint

### ISSUE THREAD

**Issue by shroudedcode** [RobinTail/express-zod-api#947]
We recently upgraded our express-zod-api major version and only now realized a bug with one of our lesser-used endpoints. It seems like the update changed how inputs on `DELETE` endpoints are interpreted.

Previously, the inputs were interpreted to come **from the request body**, and the OpenAPI schema also reflected that.

Now, the inputs are interpreted to come **from the query parameters**, with the OpenAPI schema also reflecting that.

I'm wondering: Was this a conscious change in behavior? Is there a way to revert back to using the request body?

Let me know if I should provide any more detailed examples!

**Comment by RobinTail** [comment]
Hello, @shroudedcode .

Yes, using the body of DELETE request is deprecated and it was removed by default in order to encourage following the best practices. However, you can still restore the previous behaviour by adjusting your configuration in part of input sources.
Here is a take from the Changelog:

> In case you have such Endpoints that rely on inputs collected from `DELETE` request body and want to continue,
>      add the following property to your configuration in order to keep the previous behavior without changes to your
>      implementation.

```yaml
inputSources: { delete: ["body", "query", "params"] }
```

More information on customizing input sources here:
https://github.com/RobinTail/express-zod-api#customizing-input-sources

Please let me know if this helped you to fix the issue, @shroudedcode

**Comment by shroudedcode** [comment]
Ah, that makes sense; I missed that part in the changelog

Thanks a lot for the quick reply! 🙌 I'm continually impressed by how much thought you're putting into this project.
